### ISSUE TITLE
JIOP Framework

### ISSUE THREAD

**Issue by jolly9190** [aauc-mechlab/JIOP#1]
There is no MLHistoryPoint.java file in history folder. Hence the file MLHistory. java gives error
"public class MLHistory extends ArrayList<MLHistoryPoint>"

**Comment by markaren** [comment]
I will have a look at it, and convert the project to a gradle project while I'm at it. 
Just out of curiosity, how did you find this library and what are your plans for it? You are the first one I know of that has used it :)

**Comment by markaren** [comment]
MLHistoryPoint is a member class of MLHistory, i.e. it has no own .java file and is declared inside MLHistory.java.

I just did a fresh clone and was able to run the Main class with some examples. So I don't get why you are getting an error

**Comment by jolly9190** [comment]
![image](https://cloud.githubusercontent.com/assets/18424098/14468174/2be01cfc-00fc-11e6-97ae-fcf768bba171.png)
check image
![image](https://cloud.githubusercontent.com/assets/18424098/14468193/40c377e0-00fc-11e6-8445-0bb41bb8b290.png)

**Comment by jolly9190** [comment]
I am doing project on hybrid BFO PSO in java.

**Comment by markaren** [comment]
Would it be possible to open the project in an IDE. I just converted the project to gradle, so you can open it in any major IDE. You can also build it by running gradle build (with gradle installed of course)

**Comment by jolly9190** [comment]
I don't know how to do that ..I know netbeans little..can you please help

**Comment by markaren** [comment]
For netbeans: tools -> plugins -> search for gradle -> install gradle plugin. 
Restart netbeans and open JIOP using open project.

**Comment by markaren** [comment]
By the way, I was not so happy with the performance of my BFO algorithm. I tried to implement it from the C# code found here https://msdn.microsoft.com/en-us/magazine/hh882453.aspx. It might be of help for you

**Comment by jolly9190** [comment]
try for firefly algorithm..
I am doing hybrid BFO PSO for optimization of KFCM for clustering

**Comment by jolly9190** [comment]
I am unable to open project in netbeans.copying th folder in net beans project and then "open existing project" does not open the project but it is seen as folder

**Comment by markaren** [comment]
![image](https://cloud.githubusercontent.com/assets/6005031/14468962/9a3c016c-00e2-11e6-9ad8-702165e8ef1c.png)

Does it not look like this, and you installed the gradle plugin?

**Comment by jolly9190** [comment]
yes it looks when I open a project in net beans which folder to open

**Comment by jolly9190** [comment]
![image](https://cloud.githubusercontent.com/assets/18424098/14469222/3d4e4ea0-0101-11e6-933c-668c606d3ac9.png)

**Comment by jolly9190** [comment]
![image](https://cloud.githubusercontent.com/assets/18424098/14469248/62e296ee-0101-11e6-9c03-ab9ed79e583d.png)

**Comment by markaren** [comment]
you haven't pulled the latest version of the master branch? Updated it an hour ago

**Comment by jolly9190** [comment]
thank you ..its downloading ..

**Comment by jolly9190** [comment]
Cannot execute run because the property "mainClass" is not defined or empty.
.git is not found in the newest pulled version

**Comment by markaren** [comment]
In order to get run working from the root application you'll need to add the application plugin to build.gradle. However, that is probably not want you want. You can on the other hand invoke run on any .java class that has a main method. I.e. the Main.java class in the project
